### PR TITLE
Code of conduct plus read.me

### PR DESCRIPTION
**Pull request by TomasRoj**
I created code of conduct file for future contributors. I also added my own how to help section. Then I updated readme so there is link to this file. feel free to comment what to change etc. And what abut making the website open source too?

### CODE REVIEW

**Comment by gilmaimon** [comment]
Looks fine to me. I am merging it, thank you.
> And what abut making the website open source too?

I am not sure what you mean. If you mean www.ardu-badge.com, then it is open source (this repo).

**Comment by TomasRoj** [comment]
Oh okay thanks! I will have time tomorrow do you need some things done? I mean some docs or something

**Comment by gilmaimon** [comment]
Currently the project is pretty much done, there are no known issues or or features in progress.
If there is anything you want to add or change, go for it (open an issue).

**Comment by TomasRoj** [comment]
Ok

**Pull request merged**
